services:
  paymybuddy-backend:
    image: localhost:5000/paymybuddy:latest
    container_name: paymybuddy
    restart: always
    depends_on:
      - paymybuddydb
    ports:
      - "8080:8080"
    networks:
      - paymybuddynetwork

  paymybuddydb:
    image: localhost:5000/mysql:latest
    container_name: paymybuddydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: paymybuddy
      MYSQL_PASSWORD: password
    volumes:
      - db_paymybuddy:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - paymybuddynetwork

volumes:
  db_paymybuddy:

networks:
  paymybuddynetwork:
    driver: bridge
